name: linux
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: source autostart.sh
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@master
